CREATE TABLE Therapist
(
Id SERIAL PRIMARY KEY,
	Name CHARACTER VARYING(30),
	Surname CHARACTER VARYING(30),
	Role CHARACTER VARYING(30)
);

CREATE TABLE Profile
(
	Id SERIAL PRIMARY KEY,
	Name CHARACTER VARYING(30),
	Surname CHARACTER VARYING(30),
	Sex CHARACTER VARYING(30),
	Age INTEGER	
);

CREATE TABLE Patient(
	Id Serial PRIMARY KEY,
	Status CHARACTER VARYING(30),
	Diagnosis CHARACTER VARYING(200),
	Treatments CHARACTER VARYING(200)
);
